# Generated by Django 3.2.6 on 2021-08-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co2',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='humidity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tvoc',
            name='updated_at',
        ),
    ]
