esphome:
  name: school-monitor
  platform: ESP32
  board: heltec_wifi_lora_32_V2

wifi:
  ssid: ...
  password: "..."

logger:

ota:

mqtt:
  broker: "test.mosquitto.org"
  port: 1883
  #username: 
  #password: 

i2c:
  sda: 4
  scl: 15

sensor:
  - platform: bme280
    temperature:
      name: "bme280-temperature"
      id: temperature
    pressure:
      name: "bme280-pressure"
      id: pressure
    humidity:
      name: "bme280-humidity"
      id: humidity
    address: 0x76
    update_interval: 60s

  - platform: ccs811
    eco2:
      name: "ccs811-co2"
      id: co2
    tvoc:
      name: "ccs811-tvoc"
      id: tvoc
    address: 0x5A
    update_interval: 60s

  - platform: duty_cycle
    pin: 17
    name: "dsm501a-1um-particles"
    id: one_um
    update_interval: 30s
    unit_of_measurement: pcs/238ml
    filters:
      - lambda: return 1.1*pow(x, 3) - 3.8*pow(x, 2) + 520*x + 0.62;
  
  - platform: duty_cycle
    pin: 36
    name: "dsm501a-25um-particles"
    id: twofive_um
    update_interval: 30s
    unit_of_measurement: pcs/238ml
    filters:
      - lambda: return 1.1*pow(x, 3) - 3.8*pow(x, 2) + 520*x + 0.62;

font:
  - file: '.\fonts\slkscr.ttf'
    id: slkscr
    size: 8

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 16
    address: 0x3C
    lambda: |-
      if (id(temperature).has_state()) {
        it.printf(0, 0, id(slkscr), "Temp. %.2f C", id(temperature).state);
      }

      if (id(pressure).has_state()) {
        it.printf(0, 10, id(slkscr), "Pressure %.2f hPa", id(pressure).state);
      }

      if (id(humidity).has_state()) {
        it.printf(0, 20, id(slkscr), "Humidity %.2f %", id(humidity).state);
      }

      if (id(co2).has_state()) {
        it.printf(0, 30, id(slkscr), "CO2: %.2f ppm", id(co2).state);
      }

      if (id(tvoc).has_state()) {
        it.printf(0, 40, id(slkscr), "TVOC: %.2f ppb", id(tvoc).state);
      }

      if (id(one_um).has_state() && id(twofive_um).has_state()) {
        it.printf(0, 50, id(slkscr), "1um %.2f, 2.5um %.2f pcs/238ml", id(one_um).state, id(twofive_um).state);
      }
      

web_server:
  port: 80