esphome:
  name: calibration
  platform: ESP32
  board: heltec_wifi_lora_32_V2

logger:
  level: DEBUG
  logs:
    sensor: NONE
    bme280.sensor: DEBUG
    ccs811: DEBUG

i2c:
  sda: 4
  scl: 15

sensor:
  - platform: bme280
    temperature:
      name: "bme280-temperature"
      id: temperature
    pressure:
      name: "bme280-pressure"
      id: pressure
    humidity:
      name: "bme280-humidity"
      id: humidity
    address: 0x76
    update_interval: 30s

  - platform: ccs811
    eco2:
      name: "ccs811-co2"
      id: co2
    tvoc:
      name: "ccs811-tvoc"
      id: tvoc
    address: 0x5A
    update_interval: 30s