esphome:
  name: gas-monitor
  platform: ESP32
  board: heltec_wifi_lora_32

wifi:
  ssid: "Ribeiro_2.4G"
  password: "99955015"

# Enable logging
logger:

mqtt:
  broker: "test.mosquitto.org"
  port: 1883

ota:
  password: Julio@123321

sensor:
  - platform: adc
    pin: 36
    id: no2
    name: "NO2"
    attenuation: 11db
    update_interval: 60s
  - platform: adc
    pin: 38
    id: nh3
    name: "NH3"
    attenuation: 11db
    update_interval: 60s
  - platform: adc
    pin: 39
    name: "CO"
    attenuation: 11db
    id: co
    update_interval: 60s
      
web_server:
  port: 80